exp_prefix: "pd"
epoch: 3
elite_ratio: 0.1
populate_num: 100
init_params: [1, 1, 1, 1]
lower_bound: [0, 0, 0, 0]
upper_bound: [10, 10, 10, 10]
init_sigma_ratio: 0.3 # initial sigma = init_sigma_ratio * (upper_bound - lower_bound)
noise_ratio: 0.01 # noise = noise_ratio * (upper_bound - lower_bound)
evaluator: "PDEvaluator"